### PR TITLE
Made credits have nested lists

### PR DESCRIPTION
**Pull request by Walkman100**
After adding lists:
image

Making a PR since I don't know if this takes up too much space, and the current one is mostly fine.

### CODE REVIEW

**Comment by deavmi** [comment]
@Walkman100 Thanks :smile:

**Comment by Walkman100** [comment]
You think it's fine like that? I thought it might look too spread out

**Comment by deavmi** [comment]
@Walkman100 no, it looks awesome. Thanks :smile:

**Comment by Walkman100** [comment]
Cool :+1:

**Pull request merged**
